"""Fifth-layer frozen contracts and synthetic test doubles.

This package deliberately contains no scheduler, subprocess runner, provider client,
or database write path.  Those belong to later fifth-layer units.
"""

from .contracts import (
    FROZEN_CONTRACT_HASHES,
    ContractSnapshotMismatch,
    ControlledClock,
    WorkflowReceipt,
    WorkflowRequest,
    WorkflowStepReceipt,
    verify_frozen_contracts,
)
from .fakes import (
    FakeAnalysis,
    FakeFoundation,
    FakeGarmin,
    FakeGmailTransport,
    FakeMail,
    FakeReceiptFactory,
)
from .foundation_adapter import (
    FoundationAdapter,
    FoundationAdapterError,
    FoundationAuditReference,
    FoundationBootstrapAlreadyCalled,
    FoundationGateResult,
)
from .scheduling_config import (
    AtomicConfigStore,
    ConfigReloadResult,
    ConfigurationIncidentEvidence,
    OrchestrationConfigError,
    OrchestrationConfigLoader,
    OrchestrationConfigSnapshot,
    SchedulerJobProjection,
    SchedulingProjectionService,
    UtcClock,
)
from .repository import (
    AlertDeliveryRecord,
    IncidentRecord,
    OrchestrationRepository,
    OrchestrationRepositoryError,
    OrchestrationSchemaIncompatible,
    SchedulerJobRecord,
    SchedulerHandoffRecord,
    SchedulerLeaseRecord,
    WorkflowRunRecord,
    WorkflowStepRecord,
)
from .domain_state_machine import (
    STEP_TERMINAL_STATES,
    STEP_TRANSITIONS,
    WORKFLOW_TERMINAL_STATES,
    WORKFLOW_TRANSITIONS,
    StepTransitionEvent,
    WorkflowTransitionEvent,
)
from .recovery_planner import (
    RecoveryContext,
    RecoveryDecision,
    plan_recovery,
)
from .subprocess_runner import DownstreamCall, DownstreamResult, SubprocessRunner
from .lease import LeaseError, LeaseManager, LeaseResult, Supervisor
from .due_scheduler import (
    DueEvaluation,
    DueEvaluator,
    DueItem,
    DueQueueService,
    SchedulerError,
    SchedulerIncident,
    SchedulerTick,
)

__all__ = [
    "FROZEN_CONTRACT_HASHES",
    "ContractSnapshotMismatch",
    "ControlledClock",
    "FakeAnalysis",
    "FakeFoundation",
    "FakeGarmin",
    "FakeGmailTransport",
    "FakeMail",
    "FakeReceiptFactory",
    "FoundationAdapter",
    "FoundationAdapterError",
    "FoundationAuditReference",
    "FoundationBootstrapAlreadyCalled",
    "FoundationGateResult",
    "AtomicConfigStore",
    "ConfigReloadResult",
    "ConfigurationIncidentEvidence",
    "OrchestrationConfigError",
    "OrchestrationConfigLoader",
    "OrchestrationConfigSnapshot",
    "SchedulerJobProjection",
    "SchedulingProjectionService",
    "UtcClock",
    "AlertDeliveryRecord",
    "IncidentRecord",
    "OrchestrationRepository",
    "OrchestrationRepositoryError",
    "OrchestrationSchemaIncompatible",
    "SchedulerJobRecord",
    "SchedulerHandoffRecord",
    "SchedulerLeaseRecord",
    "WorkflowRunRecord",
    "WorkflowStepRecord",
    "STEP_TRANSITIONS",
    "STEP_TERMINAL_STATES",
    "WORKFLOW_TRANSITIONS",
    "WORKFLOW_TERMINAL_STATES",
    "StepTransitionEvent",
    "WorkflowTransitionEvent",
    "RecoveryContext",
    "RecoveryDecision",
    "plan_recovery",
    "DownstreamCall",
    "DownstreamResult",
    "SubprocessRunner",
    "LeaseError",
    "LeaseManager",
    "LeaseResult",
    "Supervisor",
    "DueEvaluation",
    "DueEvaluator",
    "DueItem",
    "DueQueueService",
    "SchedulerError",
    "SchedulerIncident",
    "SchedulerTick",
    "WorkflowReceipt",
    "WorkflowRequest",
    "WorkflowStepReceipt",
    "verify_frozen_contracts",
]
